List<String> journalPrompts = [
  "What are you grateful for today?",
  "Describe a moment that made you smile today.",
  "What challenged you today, and how did you handle it?",
  "Write about a goal you're working towards.",
  "Reflect on something you learned recently.",
  "Describe your ideal day.",
  "Write a letter to your future self.",
  "How do you feel right now, and why?",
  "What's something you're looking forward to?",
  "Describe a place that makes you feel calm.",
  "What's one thing you want to improve about yourself?",
  "Write about a book, article, or podcast that inspired you.",
  "How do you take care of your mental health?",
  "What's a small victory you had today?",
  "What's something you wish you had more time for?",
  "What's something you're proud of accomplishing this week?",
  "Write about a skill you'd like to develop.",
  "Describe your perfect weekend.",
  "Reflect on a mistake you made and what you learned from it.",
  "What's your favorite way to relax?",
  "Write a gratitude list.",
  "Describe your favorite season and why you love it.",
  "Write about a recent adventure or outing.",
  "How do you handle stress?",
  "What's something you want to learn more about?",
  "Reflect on a recent conversation that impacted you.",
  "Write a bucket list of things you want to do in your lifetime.",
  "What's a new hobby you'd like to try?",
  "Describe a time when you felt proud of yourself.",
  "What's one habit you want to break?",
  "Write about a childhood memory.",
  "How do you stay motivated when facing challenges?",
  "What's something that made you laugh today?",
  "Describe your morning routine.",
  "What's one thing you're excited about for tomorrow?",
  "Write about a mentor or role model who inspires you.",
  "How do you practice self-care?",
  "What's a topic you enjoy learning about?",
  "Write about a time when you overcame a fear.",
  "What's your favorite way to spend time alone?",
  "Describe a lesson you learned from a failure.",
  "What's one thing you've been procrastinating on?",
  "Write a letter to someone you admire.",
  "What's a movie or TV show that had an impact on you?",
  "Reflect on your proudest moment.",
  "Describe your dream job.",
  "What's a recent act of kindness you witnessed or experienced?",
  "Write about a skill or talent you have.",
  "How do you practice mindfulness?",
  "What's a cause or issue you're passionate about?",
  "Describe your favorite childhood toy.",
  "Write about a time when you felt inspired.",
  "What's one thing you can do to improve your health?",
  "Reflect on a time when you felt grateful for someone's help.",
  "Write about a place you'd love to travel to.",
  "What's your favorite way to exercise?",
  "Describe your favorite holiday and why you love it.",
  "Write about a moment when you felt truly alive.",
  "What's a challenge you've overcome in the past year?",
  "How do you define success?",
  "What's a skill you'd like to teach others?",
  "Write about a lesson you learned from a mistake.",
  "What's your favorite thing about yourself?",
  "Describe your dream vacation.",
  "Write about a time when you made a difference in someone's life.",
  "How do you stay focused and productive?",
  "What's one thing you wish you could change about the world?",
  "Reflect on a time when you felt proud of a friend or family member.",
  "Write about a fear you'd like to conquer.",
  "What's a quote that resonates with you?",
  "Describe your favorite meal.",
  "Write about a time when you felt inspired by nature.",
  "How do you handle setbacks?",
  "What's something you've always wanted to learn but haven't yet?",
  "Reflect on a time when you felt truly appreciated.",
  "Write about a time when you felt at peace with yourself.",
  "What's one thing you'd like to achieve in the next month?",
  "Describe your ideal morning routine.",
  "Write about a challenge you're currently facing and how you plan to overcome it.",
  "How do you practice gratitude in your daily life?",
  "What's a childhood dream you never pursued?",
  "Reflect on a time when you showed kindness to someone.",
  "Write about a goal you've achieved recently.",
  "What's a quality you admire in others?",
  "Describe a time when you felt confident.",
  "How do you stay positive during tough times?",
  "What's a new skill you'd like to learn this year?",
  "Write about a time when you felt proud of your resilience.",
  "What's a song that always lifts your spirits?",
  "Describe your favorite way to spend a lazy day.",
  "Reflect on a time when you had to step out of your comfort zone.",
  "What's one thing you'd like to change about yourself?",
  "Write about a time when you felt supported by a friend or family member.",
  "How do you handle self-doubt?",
  "What's a project or goal you're currently working on?",
  "Describe your favorite way to unwind after a long day.",
  "Write about a time when you felt inspired by someone younger than you.",
  "What's one thing you appreciate about your life right now?",
  "Reflect on a time when you felt proud of your accomplishments.",
  "What's a book that changed your perspective on life?",
  "Write about a time when you felt overwhelmed but persevered.",
  "What are you grateful for today?",
  "What made you smile today?",
  "What challenged you today?",
  "Write about a recent accomplishment.",
  "Describe a place you would like to visit.",
  "Write a letter to your future self.",
  "What is something you would like to learn?",
  "Write about a happy memory from your childhood.",
  "What are your top priorities for the week?",
  "What is something you're looking forward to?",
  "Describe your ideal day.",
  "Write about a book or article you recently read.",
  "What are your strengths?",
  "What are your weaknesses and how can you work on them?",
  "Write about a time you overcame a fear.",
  "What is something that inspires you?",
  "Describe a recent dream you had.",
  "Write about a difficult decision you had to make.",
  "What is something that made you proud of yourself recently?",
  "Describe your morning routine.",
  "Write about a favorite hobby or activity.",
  "What is a goal you're currently working towards?",
  "What is your favorite quote and why?",
  "Write about a person who has had a significant impact on your life.",
  "What are your favorite ways to relax?",
  "Write about a time you felt grateful for your health.",
  "Describe a recent act of kindness you witnessed or experienced.",
  "What is a habit you would like to cultivate?",
  "Write about a time you failed and what you learned from it.",
  "What is something that made you laugh today?",
  "Describe a moment when you felt truly alive.",
  "What is your favorite thing about yourself?",
  "Write about a time you helped someone.",
  "What is your favorite childhood memory?",
  "What are you passionate about?",
  "Write a list of things you want to accomplish in the next year.",
  "What is something you would like to improve about yourself?",
  "Describe a favorite family tradition.",
  "Write about a recent adventure.",
  "What are you most proud of in your life so far?",
  "What does success mean to you?",
  "Write about a time you felt grateful for nature.",
  "Describe a time you stepped out of your comfort zone.",
  "What is a skill you would like to develop?",
  "Write about a recent act of courage.",
  "What are your favorite ways to practice self-care?",
  "What is something you regret?",
  "Write about a time you felt inspired by someone.",
  "What is something you are excited about for the future?",
  "Describe a recent breakthrough or realization you had.",
  "What is something you would like to achieve in the next month?",
  "Write about a time you felt proud of someone else.",
  "What is a goal you have achieved recently?",
  "Describe your ideal vacation.",
  "What is something that always makes you feel better when you're sad?",
  "Write about a time you felt grateful for friendship.",
  "What is something you would like to change about the world?",
  "Describe a recent experience that taught you something new.",
  "What is a challenge you are currently facing?",
  "Write about a time you felt truly appreciated.",
  "What is a favorite memory from your teenage years?",
  "Describe a recent moment of serenity or peace.",
  "What is something you would like to accomplish in the next five years?",
  "Write about a time you felt proud to be yourself.",
  "What is a quality you admire in others?",
  "Describe a recent act of generosity you witnessed or experienced.",
  "What is something you would like to do more often?",
  "Write about a time you felt grateful for your home.",
  "What is a decision you made that changed your life?",
  "Describe a recent experience of growth or personal development.",
  "What is something you are thankful for about your job or career?",
  "Write about a time you felt grateful for your education.",
  "What is something you have learned from a mistake?",
  "Describe a recent achievement you are proud of.",
  "What is a cause you feel passionate about?",
  "Write about a time you felt grateful for your family.",
  "What is something you would like to learn about yourself?",
  "Describe a recent act of bravery or perseverance.",
  "What is a goal you have set for yourself recently?",
  "Write about a time you felt grateful for your community.",
  "What is a favorite memory from your childhood summers?",
  "Describe a recent moment of joy or happiness.",
  "What is something you would like to accomplish in the next decade?",
  "Write about a time you felt grateful for your health.",
  "What is a lesson you learned from a failure?",
  "Describe a recent experience of overcoming a challenge.",
  "What is something you appreciate about your friendships?",
  "Write about a time you felt proud of a friend or family member.",
  "What is a favorite memory from a past relationship?",
  "Describe a recent experience of kindness or compassion.",
  "What is something you would like to learn about the world?",
  "Write about a time you felt proud to be part of a team.",
  "What is a habit you would like to break?",
  "Describe a recent experience of feeling inspired or motivated.",
  "What is something you are looking forward to in the near future?",
  "Write about a time you felt grateful for your job or career.",
  "What is a decision you regret making?",
  "Describe a recent moment of contentment or satisfaction.",
  "What is something you would like to improve about your health?",
  "Write about a time you felt proud of your accomplishments.",
  "What is a skill you would like to master?",
  "Describe a recent experience of feeling confident or empowered.",
  "What is something you appreciate about your family?"];

getUserTypeFirebase() {
  return journalPrompts;
}

